#!/bin/bash -l
#PBS -l walltime=48:00:00
#PBS -l nodes=1:ppn=36:cascadelake
#PBS -l pmem=5gb
#PBS -N Slope_Global_Nested_3
#PBS -A lp_uncertainty_quantification


module purge
module load matlab/R2019a
cd julia-1.5.0/bin/
./julia /vsc-hard-mounts/leuven-user/330/vsc33032/.julia/dev/MultilevelEstimators/applications/SPDE/Run_Beam_sigma_Supermesh_FULL_HIER.jl 2>&1 | tee /vsc-hard-mounts/leuven-user/330/vsc33032/RunReports/Beam_hpc_25032022_SUPERMESH_FULL_pmlqmc_01.txt

